language: php
php:
  - '5.6'
  - '7.0'

env:
  - PHPUNIT_OPTION="--coverage-clover build/logs/clover.xml"

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit ${PHPUNIT_OPTION}

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter
