language: php
php:
  - '5.6'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-php build/cov/coverage-${component_name}.cov

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v