language: php
php:
  - '5.6'

addons:
    code_climate:
        repo_token: $code_clime_token

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

after_failure:
  - travis_retry php vendor/bin/coveralls -v
